# Generated by Django 5.0.4 on 2024-05-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0002_alter_document_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='case_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handle_units.case'),
        ),
    ]
