# Generated by Django 5.0.4 on 2024-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0003_alter_document_case_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court_establishment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
