# Generated by Django 5.0.4 on 2024-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0004_case_court_establishment_case_district_case_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='year',
            field=models.IntegerField(),
        ),
    ]
