# Generated by Django 5.0.4 on 2024-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0006_alter_case_fir_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='filed',
        ),
        migrations.AlterField(
            model_name='case',
            name='affidavit_vakalat',
            field=models.CharField(max_length=20),
        ),
    ]
