# Generated by Django 5.0.4 on 2024-06-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle_units', '0008_customuser_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
